# Generated by Django 4.2 on 2025-03-13 09:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advocate', '0002_advocateavailability'),
        ('legaladvocapp', '0011_tbluser_reg_purpose'),
        ('adminapp', '0004_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaladvocapp.tbladvocate')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaladvocapp.tbluser_reg')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_on', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='legaladvocapp.tbluser_reg')),
            ],
        ),
        migrations.CreateModel(
            name='client_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaladvocapp.tbluser_reg')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.CharField(choices=[('client', 'Client'), ('advocate', 'Advocate')], max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_files/')),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaladvocapp.tbladvocate')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.client_case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaladvocapp.tbluser_reg')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaladvocapp.tbladvocate')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advocate.advocateavailability')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaladvocapp.tbluser_reg')),
            ],
        ),
        migrations.CreateModel(
            name='advocate_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=25)),
                ('payment_status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Payment Completed', 'Payment Completed')], default='Not Paid', max_length=25)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaladvocapp.tbladvocate')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.client_case')),
            ],
        ),
    ]
