# Generated by Django 4.2 on 2025-01-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_court'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='court',
            new_name='courtname',
        ),
    ]
