# Generated by Django 4.2 on 2025-02-24 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legaladvocapp', '0007_alter_tbluser_reg_phone_number'),
        ('adminapp', '0004_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseno', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('result', models.TextField()),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaladvocapp.tbladvocate')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.court')),
            ],
        ),
    ]
