# Generated by Django 4.2 on 2025-03-13 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legaladvocapp', '0011_tbluser_reg_purpose'),
        ('advocate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocateAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('time_slot', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaladvocapp.tbladvocate')),
            ],
            options={
                'unique_together': {('advocate', 'day', 'time_slot')},
            },
        ),
    ]
