# Generated by Django 4.2 on 2025-01-28 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblUser_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('keyuser', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tblUser_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaladvocapp.tbluser_log')),
            ],
        ),
    ]
