# Generated by Django 4.2 on 2025-01-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legaladvocapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbladvocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='advocate_photos/')),
                ('age', models.PositiveIntegerField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='advocate_certificates/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('enrollment_year', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=200)),
                ('practice_description', models.TextField()),
                ('office_location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=8)),
                ('sitting_rate', models.FloatField(max_length=50)),
                ('bc_number', models.CharField(max_length=50, unique=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaladvocapp.tbluser_log')),
            ],
        ),
    ]
