# Generated by Django 4.2 on 2025-01-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaladvocapp', '0002_tbladvocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbladvocate',
            name='bcnumber',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
