# Generated by Django 4.2 on 2025-02-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaladvocapp', '0003_tbladvocate_bcnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbladvocate',
            name='bc_number',
        ),
        migrations.AlterField(
            model_name='tbladvocate',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
