# Generated by Django 4.2 on 2025-02-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaladvocapp', '0004_remove_tbladvocate_bc_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbladvocate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=8),
        ),
    ]
