# Generated by Django 4.2 on 2025-02-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaladvocapp', '0005_alter_tbladvocate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbladvocate',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbladvocate',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
