# Generated by Django 4.2 on 2025-02-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaladvocapp', '0006_alter_tbladvocate_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser_reg',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
