# Generated by Django 4.2 on 2025-03-03 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_help'),
        ('legaladvocapp', '0007_alter_tbluser_reg_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbladvocate',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.category'),
            preserve_default=False,
        ),
    ]
