# Generated by Django 4.2 on 2025-03-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaladvocapp', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbladvocate',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=25),
        ),
    ]
