# Generated by Django 4.2 on 2025-03-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaladvocapp', '0010_tbladvocate_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser_reg',
            name='purpose',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
