# Generated by Django 4.2 on 2025-03-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaladvocapp', '0011_tbluser_reg_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
